spring:
  application:
    name: consumer-sample
  cloud:
    nacos:
      server-addr: 192.168.168.168:8848
      username: nacos
      password: nacos

server:
  port: 8080
# 自定义配置feign的属性
feign:
  client:
    config:
      default:
        logger-level: FULL
        connect-timeout: 5000
        read-timeout: 5000
logging:
  level:
    com.lizhengpeng.bigger.java.ProviderFeign: DEBUG